name: noteapp
description: A new Flutter project.

publish_to: 'none'

version: 1.0.5+6

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: any
  path: any
  image_picker: ^0.8.6
  google_mlkit_text_recognition: any
  flutter_staggered_grid_view: ^0.4.0
  sqflite: any
  path_provider: ^2.0.11
  provider: any
  image_cropper: ^3.0.1
  share_plus: ^4.5.3
  shared_preferences: any
  encrypt: ^5.0.1
  fluttertoast: ^8.2.1
  local_auth: any
  local_auth_android: any
  flutter_secure_storage: ^8.0.0
  permission_handler: ^10.2.0
  device_info_plus: ^10.1.0
  record_mp3: ^3.0.0
  lottie: ^2.3.2
  audio_waveforms: ^1.0.4

  firebase_auth: ^4.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/note.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
